### ISSUE TITLE
Float array writing and reading does not work

### ISSUE THREAD

**Issue by vilim** [bhoeckendorf/pyklb#2] opened 2016-05-23 12:26 UTC
Hello,

I am trying to use the KLB format to store intermediate steps in processing of imaging datasets, so far I have managed by hacking through the old version of the python wrapper (which was on bitbucket). I changed a few bits to work with python3 and fixed some bugs, but reading ROIs did not work.

Now I tried this version (the current one on github), where reading ROIs works, but trying to store multidimensional float arrays fails.

Python 3.5:

```
import pyklb
test_float = np.random.randn(4,4,4,4).astype(np.float32)
test_int = (test_float*10).astype(np.int16)
```

Now,
`pyklb.writefull(test_float, 'test_float.klb')`
fails with errors `ERROR: workerfunc: compressing data at block 0 with bzip2. Error code -8
`
while
`pyklb.writefull(test_int, 'test_int.klb')`
works.

The same error appears both on Windows 10 and OS X 10.11

In the old version there was a bug with data type conversion between numpy and ctypes, but that seems to be fixed now. What else could be wrong?

Thanks,
Vilim

**Comment by stuarteberg** [comment] 2016-05-26 14:14
It appears that bzip is complaining, with error code -8.  Here are the error codes from `bzlib.h`:

``` c
#define BZ_RUN               0
#define BZ_FLUSH             1
#define BZ_FINISH            2

#define BZ_OK                0
#define BZ_RUN_OK            1
#define BZ_FLUSH_OK          2
#define BZ_FINISH_OK         3
#define BZ_STREAM_END        4
#define BZ_SEQUENCE_ERROR    (-1)
#define BZ_PARAM_ERROR       (-2)
#define BZ_MEM_ERROR         (-3)
#define BZ_DATA_ERROR        (-4)
#define BZ_DATA_ERROR_MAGIC  (-5)
#define BZ_IO_ERROR          (-6)
#define BZ_UNEXPECTED_EOF    (-7)
#define BZ_OUTBUFF_FULL      (-8)
#define BZ_CONFIG_ERROR      (-9)
```

I don't know exactly which bzip2 functions the klb library is using, but the documentation for `BZ2_bzBuffToBuffCompress()` [says the following](http://www.bzip.org/1.0.3/html/util-fns.html):

> If the compressed data won't fit, `*destLen` is unchanged, and `BZ_OUTBUFF_FULL` is returned.

So I guess you're providing a destination buffer somewhere that isn't actually big enough to hold the "compressed" data.  That's not a huge surprise in this case.  The user is trying to "compress" random data.  Random data doesn't compress -- it probably ends up even larger after bzip processes it!

**Comment by nclack** [comment] 2016-05-26 15:19
I added a [test](https://bitbucket.org/fernandoamat/keller-lab-block-filetype/src/c849002dc3a6683bb52bb531d09e4febab07d666/src/test/write_float_bz2.c?at=master&fileviewer=file-view-default) to the klb library repository to see if I could reproduce the issue on the c side.

It fails in a similar fashion:

```
ERROR: workerfunc: compressing data at block ERROR: workerfunc: compressing data at block 1 with bzip2. Error code -8
ERROR: workerfunc: compressing data at block 2 with bzip2. Error code -8
0 with bzip2. Error code -8
ERROR: workerfunc: compressing data at block 3 with bzip2. Error code -8
Error during BZIP compression of one of the blocks
Got error code: 2
    write(src)
```

Similarly, ZLIB fails:

```
ERROR: workerfunc: uncompressing data at block 1 with zlib. Error code -5
```

However, NONE works fine.  So, my guess is that a workaround for the time being would be to forego compression for float data.

**Comment by nclack** [comment] 2016-05-26 15:26
Opened a [ticket](https://bitbucket.org/fernandoamat/keller-lab-block-filetype/issues/1/bzip2-and-zip-compression-of-float-data) on the [klb bitbucket repository](https://bitbucket.org/fernandoamat/keller-lab-block-filetype).

**Comment by stuarteberg** [comment] 2016-05-26 15:33
> a workaround for the time being would be to forego compression for float data.

I think that would be overkill, and bad for users who use float data.  I think the error here is not surprising in retrospect:  Random data will not compress, so we need to leave plenty of headroom in the output buffer.  The [bzip2 man page](http://www.bzip.org/1.0.5/bzip2.txt) says that the size of "compressed" random data will be "about" 8.05 bits per input byte, but I doubt that you can rely on that ratio for such tiny tiny data sizes.

In the klb library, here's the [line of code](https://bitbucket.org/fernandoamat/keller-lab-block-filetype/src/c849002dc3a6683bb52bb531d09e4febab07d666/src/klb_imageIO.cpp?at=master&fileviewer=file-view-default#klb_imageIO.cpp-1612) the chooses how big the output buffer should be:

``` c++
blockSizeBytes = ceil(((float)blockSizeBytes) * 1.05f + 50.0f );
```

I think it should be changed to add a little extra headroom for very tiny input buffers.  Alternatively, it might be enough to just declare in the documentation that klb doesn't support random data.

Of course, if you are able to reproduce this for larger input data sizes, then maybe I'm misunderstanding the problem.  But so far, the test here is using only 1024 bytes.

**Comment by stuarteberg** [comment] 2016-05-26 15:51
Quoting myself:

> But so far, the test here is using only 1024 bytes.

Actually, I'm using the wrong number there. The total size of the data doesn't matter -- in KLB, it's the block size that matters.  In Nathan's test, that's only 256 bytes.  When I try to compress random data that small, here's what I see:

``` python
In [11]: import numpy as np

In [12]: a = np.random.random((4,4,4)).astype(np.float32)

In [13]: with open('random.data', 'w') as f:
    f.write(np.getbuffer(a))
   ....:

In [14]: !bzip2 random.data

In [15]: !ls -lh random.data.bz2
-rw-r--r--  1 bergs  wheel   378B May 26 11:40 random.data.bz2

In [16]: len(np.getbuffer(a))
Out[16]: 256
```

So in that test, the "compresed" data was 378 bytes, but klb would have only reserved an output buffer of `256 * 1.05 == 319` bytes.  The compression ratio starts to improve if you use larger data, though.

**Comment by bhoeckendorf** [comment] 2016-05-26 17:00
Strangely, I can use the Java and Julia wrappers to compress and write 4x4x4x4 float32 klb files just fine. They call the same function @nclack uses in his test:

> I added a [test](https://bitbucket.org/fernandoamat/keller-lab-block-filetype/src/c849002dc3a6683bb52bb531d09e4febab07d666/src/test/write_float_bz2.c?at=master&fileviewer=file-view-default) to the klb library repository to see if I could reproduce the issue on the c side.

**Comment by stuarteberg** [comment] 2016-05-26 17:02
> Strangely, I can use the Java and Julia wrappers to compress and write 4x4x4x4

Do the Java wrappers choose a different default block size than the Python wrappers?

**Comment by bhoeckendorf** [comment] 2016-05-26 17:02
> Do the Java wrappers choose a different default block size than the Python wrappers?

no

**Comment by stuarteberg** [comment] 2016-05-26 17:03
It's the block size that matters, so I guess that explains the difference.

**Comment by bhoeckendorf** [comment] 2016-05-26 17:04
> It's the block size that matters, so I guess that explains the difference.

Not sure I understand. The default block size is the same in each case.

**Comment by stuarteberg** [comment] 2016-05-26 17:08
Oh, crap, sorry, I'm not paying attention.  "No" meant "no, they're not different".  Well, I'm stumped.  Are you sure the data in your test is _really_ random, and really float32 (not float64)?

**Comment by nclack** [comment] 2016-05-26 17:09
Changing to

``` c
   blockSizeBytes = ceil(((float)blockSizeBytes) * 2.0f + 50.0f );
```

works for writing with BZIP and ZIP.  I did a little fiddling with the scaling factor (i.e. 2.0 above).  1.33 was about the threshold for this test.  I left it at 2.0 to be on the safe side.

The decompression routine was also broken for the case when the "compressed" size is actually larger than the uncompressed size.

**Comment by nclack** [comment] 2016-05-26 17:10
Tests pass in the bitbucket now.

**Comment by bhoeckendorf** [comment] 2016-05-26 17:11
> Oh, crap, sorry, I'm not paying attention. "No" meant "no, they're not different". Well, I'm stumped. Are you sure the data in your test is really random, and really float32 (not float64)?

You're right. My bad this time. :)
The data was not random at all and hence compressed really well. So forget what I wrote.

**Comment by bhoeckendorf** [comment] 2016-05-27 17:14
I can confirm that the problem is fixed. I'll recompile the binaries we use for the Java wrapper (which are downloaded by the Python wrapper as a quick solution to the problem of making setup.py and CMake interact nicely) and then close the issue. Until then, using a build of the main library from its most recent [source code](https://bitbucket.org/fernandoamat/keller-lab-block-filetype) solves the problem too.

Thanks a lot @stuarteberg and @nclack for your time and help!

**Closed as completed** 2021-05-17 17:43 UTC
